import Head from "next/head";
import Navigation from "./components/navigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Brata Darmawan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-me.ico" />
      </Head>
      <main className="flex w-screen flex-col">
        <Navigation />
        <div className="flex h-auto w-screen flex-col items-center justify-center bg-red-500">
          <h1 className="text-4xl font-bold">Hello There</h1>
          <h1 className="text-4xl font-bold">Hello There</h1>
        </div>
      </main>
    </>
  );
}
